services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: vendas-ceasa-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - vendas-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # API FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vendas-ceasa-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - vendas-network

  # PHPMyAdmin (opcional para desenvolvimento)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vendas-ceasa-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
    networks:
      - vendas-network
    profiles:
      - dev

volumes:
  mysql_data:
    driver: local

networks:
  vendas-network:
    driver: bridge
