"""adicionar_fluxo_caixa_fifo

Revision ID: 9f28235c2e93
Revises: 800e4b6e2855
Create Date: 2025-08-07 16:58:10.874755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f28235c2e93'
down_revision: Union[str, Sequence[str], None] = '800e4b6e2855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
