"""Corrigir campos estoque - adicionar fornecedor e quantidade_atual

Revision ID: 800e4b6e2855
Revises: 6cb11f60903a
Create Date: 2025-08-07 16:15:20.593453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '800e4b6e2855'
down_revision: Union[str, Sequence[str], None] = '6cb11f60903a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entradas_estoque', sa.Column('preco_custo', sa.DECIMAL(precision=10, scale=2), nullable=False))
    op.add_column('entradas_estoque', sa.Column('fornecedor', sa.String(length=200), nullable=True))
    op.drop_column('entradas_estoque', 'valor_unitario')
    op.add_column('inventarios', sa.Column('quantidade_atual', sa.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('inventarios', sa.Column('data_ultima_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('inventarios', 'data_registro')
    op.drop_column('inventarios', 'quantidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventarios', sa.Column('quantidade', mysql.DECIMAL(precision=10, scale=3), nullable=False))
    op.add_column('inventarios', sa.Column('data_registro', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.drop_column('inventarios', 'data_ultima_atualizacao')
    op.drop_column('inventarios', 'quantidade_atual')
    op.add_column('entradas_estoque', sa.Column('valor_unitario', mysql.DECIMAL(precision=10, scale=2), nullable=False))
    op.drop_column('entradas_estoque', 'fornecedor')
    op.drop_column('entradas_estoque', 'preco_custo')
    # ### end Alembic commands ###
